### ISSUE TITLE
OBS Plugin on linux doesn't connect to app

### ISSUE THREAD

**Issue by jms1989** [dev47apps/droidcam-obs-plugin#11]
I've got the app working and can connect to it in my browser but OBS refuses to connect to it.

It spews this in the logs over and over.; 

```
04:35:05 PM.042: [DroidCamOBS] release video_decoder
04:35:05 PM.042: [DroidCamOBS] ~decoder alloc_count=0
04:35:05 PM.085: [DroidCamOBS] starting video via socket 63
04:35:05 PM.085: [DroidCamOBS] create video decoder
04:35:05 PM.090: [DroidCamOBS] data packet too large at 540291120!
04:35:05 PM.090: [DroidCamOBS] closing failed video socket 63
```

I've tried googling and found nothing that helps.

**Comment by aramg** [comment]
I think you are connecting to the regular DroidCam app and not the OBS app.
Please take a closer look at the all the text on the OBS plugin webpage.

**Comment by jms1989** [comment]
I see it now. Didn't realize there was a difference.
