### ISSUE TITLE
Windows Plugin doesn't detect OBS installation

### ISSUE THREAD

**Issue by Romarain** [dev47apps/droidcam-obs-plugin#6]
Hi,

When installing the plugin, I get this error :

![2020-07-02_20h35m41s_DroidCamOBS Plugin Setup](https://user-images.githubusercontent.com/22033256/86397544-4bc3c100-bca4-11ea-82e5-84c33ed047df.jpg)

Fact is OBS Streamlabs x64 0.22.0 is installed in my computer.

**Comment by Romarain** [comment]
Aaaah, sorry, your plugin is for OBS Studio (=/= OBS Streamlabs) ! :(
Oops.

**Comment by aramg** [comment]
Yep see #4
